### ISSUE TITLE
关于lncRNA的相似性融合

### ISSUE THREAD

**Issue by su-jinghan** [yeyetuowoyi/HBRWRLDA#2]
您好！
您的lncRNA的表达相似性是根据什么原理计算的呢？它的形状是（447，53）还是（447，447）呢？
如果shape是（447，53）您又是如何与高斯相互作用谱核相似性融合的呢？

**Comment by yeyetuowoyi** [comment]
lncRNA是根据lncRNA的表达谱来计算，它的数学形式是一个(447,53）的矩阵，具体可以这样理解每个lncRNA有53个特征，每个特征有一个得分，然后计算每两个lncRNA之间每个特征之间的系数得分来得出它们的相似性，相似性矩阵是(447，447)，每行代表的是每个lncRNA与其他446个lncRNA的相似性得分，高斯相互作用相似性是根据原来的lncRNA与疾病联系矩阵得出，也是(447，447）的矩阵



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月26日(周六) 下午4:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [yeyetuowoyi/HBRWRLDA] 关于lncRNA的相似性融合 (Issue #2)




 
您好！
 您的lncRNA的表达相似性是根据什么原理计算的呢？它的形状是（447，53）还是（447，447）呢？
 如果shape是（447，53）您又是如何与高斯相互作用谱核相似性融合的呢？

**Comment by su-jinghan** [comment]
好的谢谢您！
